//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LasCarasDeHeraldo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historico
    {
        public int Id { get; set; }
        public string Comentario { get; set; }
        public int Reclamo_Id { get; set; }
        public int Estado_Id { get; set; }
        public int Area_Id { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Reclamo Reclamo { get; set; }
    }
}
