//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LasCarasDeHeraldo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReclamosEntities : DbContext
    {
        public ReclamosEntities()
            : base("name=ReclamosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaSet> AreaSets { get; set; }
        public virtual DbSet<EstadoSet> EstadoSets { get; set; }
        public virtual DbSet<HistoricoSet> HistoricoSets { get; set; }
        public virtual DbSet<ReclamoSet> ReclamoSets { get; set; }
        public virtual DbSet<TipoUsuarioSet> TipoUsuarioSets { get; set; }
        public virtual DbSet<UsuarioSet> UsuarioSets { get; set; }
    }
}
